version: "2"

services:

  db:
    image: postgres:9.4-alpine
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=taiga_password
      - POSTGRES_DB=taiga
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  taiga-back:
    build: back
    volumes:
      - ./back/local.py:/taiga-back/settings/local.py

##  web:
##    build: web
##    ports:
##      - "8089:80"
##      - "443:443"
##    read_only: true
##    restart: unless-stopped
##    volumes:
##      # This directory must have cert files if you want to enable SSL
##      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true
