version: "3.3"

services:

  db:
    image: postgres:9.4-alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=taiga
      - POSTGRES_PASSWORD=taiga_password
      - POSTGRES_DB=taiga

  taiga-back:
    build: taiga-back
    restart: unless-stopped
    volumes:
      - static_data:/taiga-back/static
      - ./taiga-back/local.py:/taiga-back/settings/local.py
      - /etc/localtime:/etc/localtime:ro

  taiga-front:
    build: taiga-front
    restart: unless-stopped
    read_only: true
    ports:
      - "8089:80"
    volumes:
      - static_data:/taiga-front-dist/static:ro
      - media_data:/taiga-front-dist/media
      - ./taiga-front/conf.json:/taiga-front-dist/dist/conf.json
      - /etc/localtime:/etc/localtime:ro

volumes:
  db_data:
  static_data:
  media_data:
